// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oazzsljjptfaatyvgzjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9henpzbGpqcHRmYWF0eXZnempuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NDg3MjgsImV4cCI6MjA2NDMyNDcyOH0.1ilXIIzgy36XKtWqzq-kE-XatnbZnaH5x8c_hOlXKOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);